id: PYSEC-0000-CVE-2023-28859
details: 'redis-py through 4.5.3 leaves a connection open after canceling an async
  Redis command at an inopportune time (in the case of a non-pipeline operation),
  and can send response data to the client of an unrelated request. NOTE: this issue
  exists because of an incomplete fix for CVE-2023-28858.'
affected:
- package:
    name: redis
    ecosystem: PyPI
    purl: pkg:pypi/redis
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 5.0.0b1
references:
- type: WEB
  url: https://github.com/redis/redis-py/pull/2641
- type: REPORT
  url: https://github.com/redis/redis-py/issues/2665
aliases:
- CVE-2023-28859
modified: "2023-03-27T12:40:00Z"
published: "2023-03-26T19:15:00Z"
